# Generated by Django 3.2 on 2021-04-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NUBANK 0000', help_text='Somente os últimos digitos', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agência', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fornecedor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='miles_currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('currency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Valor do milhar',
                'verbose_name_plural': 'Valor do milhar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ticket_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conta_vinculada', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Conta Vinculada',
                'verbose_name_plural': 'Contas vinculadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tickets_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da emissão')),
                ('localizador', models.CharField(max_length=6, unique=True)),
                ('taxas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adicional', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obs', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='bilhetes')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.company')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.card_used', verbose_name='Cartão Usado')),
                ('conta_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.ticket_account')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.distribute')),
                ('milhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.miles_currency')),
            ],
            options={
                'verbose_name': 'Lista de emissões',
                'verbose_name_plural': 'Lista de emissões',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ticket_pax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('E-Ticket', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('age', models.CharField(choices=[('Adulto', 'Adulto'), ('Criança', 'Criança'), ('Bebê', 'Bebê')], max_length=50, verbose_name='Tipo de passageiro(a)')),
                ('milhas', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Total de Milhas')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilita_voos.tickets_list')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'managed': True,
            },
        ),
    ]
